CC=gcc
CFLAGS= -std=gnu99 -Wall
LDLIBS = -lpthread -lm -lrt 

all: aio2018.c


#aioexample: aioexample.c 
	#${CC} ${CFLAG} -g -o aioexample aioexample.c -lrt


.PHONY: clean all

clean:
	-rm -f aio2018

