CC=gcc
CFLAGS= -std=gnu99 -Wall

all: prog22a.c prog22b.c  


prog22a: prog22a.c 
	${CC} ${CFLAG} -o prog22a prog22a.c

prog22b: prog22b.c 
	${CC} ${CFLAG} -o prog22b prog22b.c




.PHONY: clean all

clean:
	-rm -f prog22a prog22b 