CC=gcc
CFLAGS= -std=gnu99 -Wall
LDLIBS = -lpthread -lm

all: prog17.c prog18.c prog19.c prog20.c 


# prog17: prog17.c 
# 	${CC} ${CFLAG} -o prog13a prog13a.c

# prog18: prog18.c 
# 	${CC} ${CFLAG} -o prog13b prog13b.c

# prog19: prog19.c 
# 	${CC} ${CFLAG} -o prog14 prog14.c

# prog20: prog20.c 
# 	${CC} ${CFLAG} -o prog15 prog15.c



.PHONY: clean all

clean:
	-rm -f prog17 prog18 prog19 prog20